# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af32aa0fba8c785241430be34ffb5f3f5bd50331cfa53b9db0f19e7e3e9b80678a5b55d042bba6424b1635c876f0d068403e21864695e0a8cdb9dc807fe55682

test:
  secret_key_base: e8a90a54606cb34b1dbec599f65fca6a05b4f48de264748faecb3e5cfbb99f382eac62d3b0df694f6cb1fd14c5840a7efff389b53dd0c7d00f1a2d2a29fa22dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
